export const WORDING = {
    ANGKA: [
      'nol ',
      'satu ',
      'dua ',
      'tiga ',
      'empat ',
      'lima ',
      'enam ',
      'tujuh ',
      'delapan ',
      'sembilan ',
      'sepuluh ',
    ],
    SATUAN: {
      BELASAN: 'belas ',
      PULUHAN: 'puluh ',
      RATUSAN: 'ratus ',
      RIBUAN: 'ribu ',
      JUTAAN: 'juta ',
      MILIARAN: 'miliar ',
      TRILIUNAN: 'triliun ',
    },
    UNIQUE: {
      SEPULUH: 10,
      SEBELAS:  11,
      DUA_PULUH: 20,
      SERATUS: 100,
      DUA_RATUS: 200,
      SERIBU: 1000,
      DUA_RIBU: 2000,
      SEPULUH_RIBU: 10000,
      SATU_JUTA: 1000000,
      SATU_MILIAR: 1000000000,
      SATU_TRILLIUN: 1000000000000,
    },
  };

export const NUMBERING = {
    ANGKA: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
      ],
      SATUAN: {
        BELASAN: 'belas ',
        PULUHAN: 'puluh ',
        RATUSAN: 'ratus ',
        RIBUAN: 'ribu ',
        JUTAAN: 'juta ',
        MILIARAN: 'miliar ',
        TRILIUNAN: 'triliun ',
      },
      UNIQUE: {
        SEPULUH: "10",
        SEBELAS:  "11",
        DUA_PULUH: "20",
        SERATUS: "100",
        DUA_RATUS: "200",
        SERIBU: "1000",
        DUA_RIBU: "2000",
        SEPULUH_RIBU: "10000",
        SATU_JUTA: "1000000",
        SATU_MILIAR: "1000000000",
        SATU_TRILLIUN: "1000000000000",
  }
};